export type SecuritySeverity = "low" | "medium" | "high" | "critical";

export type SecurityFamily =
  | "library_structure"
  | "library_article"
  | "library_search"
  | "library_tooltip"
  | "test_payload"
  | "test_search"
  | "test_practice"
  | "test_explanation";

export type SecurityAction =
  | "log"
  | "soft_throttle"
  | "content_cooldown"
  | "content_lock";

export const SECURITY_SETTINGS_DEFAULTS = {
  SECURITY_SCRAPING_PROTECTION_ENABLED: "true",
  SECURITY_TELEGRAM_ALERTS_ENABLED: "true",
  ENABLE_TELEGRAM_SECURITY_ALERTS: "true",
  SECURITY_TELEGRAM_CHAT_ID: "",
  SECURITY_WATERMARKING_ENABLED: "true",
  SECURITY_IP_BLOCKING_ENABLED: "true",
  SECURITY_BLOCKED_IP_SCOPE: "all_requests",
  SECURITY_DEACTIVATE_ALSO_BLOCK_IP: "true",
  SECURITY_AUTO_DEACTIVATE_ROLE_SCOPE: "user",
  SECURITY_FREE_USER_TOTAL_TEST_CAP: "4",
  SECURITY_FREE_USER_TOTAL_TEST_CAP_GRANDFATHER_EXISTING: "true",
  SECURITY_TEST_PROTECTION_ROLE_SCOPE: "user",
  SECURITY_ALL_USER_DAILY_TEST_CAP: "20",
  SECURITY_DAILY_TEST_CAP_SPAM_WINDOW_SECONDS: "300",
  SECURITY_DAILY_TEST_CAP_SPAM_THRESHOLD: "10",
  SECURITY_TEST_CREATION_ABUSE_WINDOW_SECONDS: "300",
  SECURITY_TEST_CREATION_ABUSE_MAX_HITS: "8",
  SECURITY_TEST_CREATION_AUTO_DEACTIVATE_ENABLED: "true",
  SECURITY_TEST_CREATION_ABUSE_STRIKE_THRESHOLD: "2",
  SECURITY_FREE_LIBRARY_DAILY_ARTICLE_CAP: "10",
  SECURITY_LIBRARY_QUOTA_COUNT_UNIQUE_ONLY: "true",
  SECURITY_LIBRARY_QUOTA_COUNT_ONLY_ARTICLE_OPENS: "true",
  SECURITY_LIBRARY_ABUSE_AUTO_DEACTIVATE_ENABLED: "true",
  SECURITY_LIBRARY_ABUSE_STRIKE_THRESHOLD: "3",
  SECURITY_LIBRARY_ABUSE_SEVERE_EXACT_ENDPOINT_HITS: "20",
  SECURITY_LIBRARY_ABUSE_SEVERE_DISTINCT_MINUTE_HITS: "24",
  SECURITY_SCORE_MEDIUM: "25",
  SECURITY_SCORE_HIGH: "60",
  SECURITY_SCORE_CRITICAL: "100",
  SECURITY_COOLDOWN_SECONDS: "300",
  SECURITY_CONTENT_LOCK_SECONDS: "1800",
  SECURITY_STRIKE_WINDOW_SECONDS: "3600",
  SECURITY_REPEAT_OFFENSE_MULTIPLIER: "2",
  SECURITY_AGGREGATION_WINDOW_SECONDS: "900",
  SECURITY_TELEGRAM_ALERT_COOLDOWN_SECONDS: "300",
  SECURITY_TELEGRAM_MIN_SEVERITY: "high",
  SECURITY_TEST_SEARCH_RESULT_LIMIT: "10",
  SECURITY_TEST_EXPLANATION_DAILY_HARD_CAP: "80",
  SECURITY_TEST_PRACTICE_DAILY_HARD_CAP: "60",
  SECURITY_LIBRARY_STRUCTURE_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_STRUCTURE_MAX_HITS: "20",
  SECURITY_LIBRARY_STRUCTURE_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_STRUCTURE_EXACT_ENDPOINT_MAX_HITS: "12",
  SECURITY_LIBRARY_STRUCTURE_SCORE_BURST: "8",
  SECURITY_LIBRARY_STRUCTURE_SCORE_EXACT_ENDPOINT: "10",
  SECURITY_LIBRARY_ARTICLE_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_ARTICLE_MAX_HITS: "16",
  SECURITY_LIBRARY_ARTICLE_SAME_TARGET_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_ARTICLE_SAME_TARGET_MAX_HITS: "6",
  SECURITY_LIBRARY_ARTICLE_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_ARTICLE_EXACT_ENDPOINT_MAX_HITS: "6",
  SECURITY_LIBRARY_ARTICLE_DISTINCT_MINUTE_MAX: "8",
  SECURITY_LIBRARY_ARTICLE_DISTINCT_HOUR_MAX: "30",
  SECURITY_LIBRARY_ARTICLE_DISTINCT_DAY_MAX: "80",
  SECURITY_LIBRARY_ARTICLE_SCORE_BURST: "12",
  SECURITY_LIBRARY_ARTICLE_SCORE_SAME_TARGET: "20",
  SECURITY_LIBRARY_ARTICLE_SCORE_EXACT_ENDPOINT: "22",
  SECURITY_LIBRARY_ARTICLE_SCORE_DISTINCT: "18",
  SECURITY_LIBRARY_SEARCH_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_SEARCH_MAX_HITS: "12",
  SECURITY_LIBRARY_SEARCH_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_SEARCH_EXACT_ENDPOINT_MAX_HITS: "8",
  SECURITY_LIBRARY_SEARCH_SCORE_BURST: "12",
  SECURITY_LIBRARY_SEARCH_SCORE_EXACT_ENDPOINT: "15",
  SECURITY_LIBRARY_TOOLTIP_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_TOOLTIP_MAX_HITS: "18",
  SECURITY_LIBRARY_TOOLTIP_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_LIBRARY_TOOLTIP_EXACT_ENDPOINT_MAX_HITS: "12",
  SECURITY_LIBRARY_TOOLTIP_SCORE_BURST: "8",
  SECURITY_LIBRARY_TOOLTIP_SCORE_EXACT_ENDPOINT: "10",
  SECURITY_TEST_PAYLOAD_WINDOW_SECONDS: "60",
  SECURITY_TEST_PAYLOAD_MAX_HITS: "12",
  SECURITY_TEST_PAYLOAD_SAME_TARGET_WINDOW_SECONDS: "60",
  SECURITY_TEST_PAYLOAD_SAME_TARGET_MAX_HITS: "5",
  SECURITY_TEST_PAYLOAD_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_TEST_PAYLOAD_EXACT_ENDPOINT_MAX_HITS: "5",
  SECURITY_TEST_PAYLOAD_DISTINCT_MINUTE_MAX: "6",
  SECURITY_TEST_PAYLOAD_DISTINCT_HOUR_MAX: "20",
  SECURITY_TEST_PAYLOAD_DISTINCT_DAY_MAX: "50",
  SECURITY_TEST_PAYLOAD_SCORE_BURST: "12",
  SECURITY_TEST_PAYLOAD_SCORE_SAME_TARGET: "18",
  SECURITY_TEST_PAYLOAD_SCORE_EXACT_ENDPOINT: "20",
  SECURITY_TEST_PAYLOAD_SCORE_DISTINCT: "18",
  SECURITY_TEST_SEARCH_WINDOW_SECONDS: "60",
  SECURITY_TEST_SEARCH_MAX_HITS: "10",
  SECURITY_TEST_SEARCH_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_TEST_SEARCH_EXACT_ENDPOINT_MAX_HITS: "6",
  SECURITY_TEST_SEARCH_SCORE_BURST: "14",
  SECURITY_TEST_SEARCH_SCORE_EXACT_ENDPOINT: "18",
  SECURITY_TEST_PRACTICE_WINDOW_SECONDS: "60",
  SECURITY_TEST_PRACTICE_MAX_HITS: "10",
  SECURITY_TEST_PRACTICE_SAME_TARGET_WINDOW_SECONDS: "60",
  SECURITY_TEST_PRACTICE_SAME_TARGET_MAX_HITS: "4",
  SECURITY_TEST_PRACTICE_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_TEST_PRACTICE_EXACT_ENDPOINT_MAX_HITS: "4",
  SECURITY_TEST_PRACTICE_DISTINCT_MINUTE_MAX: "6",
  SECURITY_TEST_PRACTICE_DISTINCT_HOUR_MAX: "20",
  SECURITY_TEST_PRACTICE_DISTINCT_DAY_MAX: "50",
  SECURITY_TEST_PRACTICE_SCORE_BURST: "15",
  SECURITY_TEST_PRACTICE_SCORE_SAME_TARGET: "18",
  SECURITY_TEST_PRACTICE_SCORE_EXACT_ENDPOINT: "18",
  SECURITY_TEST_PRACTICE_SCORE_DISTINCT: "16",
  SECURITY_TEST_EXPLANATION_WINDOW_SECONDS: "60",
  SECURITY_TEST_EXPLANATION_MAX_HITS: "12",
  SECURITY_TEST_EXPLANATION_SAME_TARGET_WINDOW_SECONDS: "60",
  SECURITY_TEST_EXPLANATION_SAME_TARGET_MAX_HITS: "5",
  SECURITY_TEST_EXPLANATION_EXACT_ENDPOINT_WINDOW_SECONDS: "60",
  SECURITY_TEST_EXPLANATION_EXACT_ENDPOINT_MAX_HITS: "5",
  SECURITY_TEST_EXPLANATION_DISTINCT_MINUTE_MAX: "8",
  SECURITY_TEST_EXPLANATION_DISTINCT_HOUR_MAX: "30",
  SECURITY_TEST_EXPLANATION_DISTINCT_DAY_MAX: "90",
  SECURITY_TEST_EXPLANATION_SCORE_BURST: "12",
  SECURITY_TEST_EXPLANATION_SCORE_SAME_TARGET: "18",
  SECURITY_TEST_EXPLANATION_SCORE_EXACT_ENDPOINT: "20",
  SECURITY_TEST_EXPLANATION_SCORE_DISTINCT: "16",

  // ── Rate Limiting (Throttle) ──────────────────────────────────────
  // These values MUST stay in sync with the in-code fallbacks in
  // src/rate-limit/app-throttler.guard.ts and the initial throttler config
  // in src/rate-limit/rate-limit.config.ts. They are used by:
  //   1. The admin Security Settings UI as the default values shown when a
  //      setting hasn't been overridden in the DB.
  //   2. The settings service fallback when no DB row exists for the key.
  // Tightened to match the post-audit defaults (brute-force defense on auth,
  // anti-scrape on library/media, cost control on AI).
  RATE_LIMIT_AI_BURST_TTL: "60",
  RATE_LIMIT_AI_BURST_MAX: "10",
  RATE_LIMIT_AI_BURST_BLOCK_DURATION: "120",
  RATE_LIMIT_LIBRARY_VIEW_TTL: "60",
  RATE_LIMIT_LIBRARY_VIEW_MAX: "30",
  RATE_LIMIT_LIBRARY_VIEW_BLOCK_DURATION: "300",
  RATE_LIMIT_AUTH_TTL: "60",
  RATE_LIMIT_AUTH_MAX: "5",
  RATE_LIMIT_AUTH_BLOCK_DURATION: "600",
  RATE_LIMIT_TEST_CREATE_TTL: "60",
  RATE_LIMIT_TEST_CREATE_MAX: "10",
  RATE_LIMIT_TEST_CREATE_BLOCK_DURATION: "300",
  RATE_LIMIT_PUBLIC_TTL: "60",
  RATE_LIMIT_PUBLIC_READ_MAX: "120",
  RATE_LIMIT_PUBLIC_WRITE_MAX: "30",
  RATE_LIMIT_PUBLIC_BLOCK_DURATION: "60",
  RATE_LIMIT_MEDIA_TTL: "60",
  RATE_LIMIT_MEDIA_MAX: "20",
  RATE_LIMIT_MEDIA_BLOCK_DURATION: "300",
  RATE_LIMIT_JOB_APP_TTL: "600",
  RATE_LIMIT_JOB_APP_MAX: "3",
  RATE_LIMIT_JOB_APP_BLOCK_DURATION: "1800",
  RATE_LIMIT_BACKOFF_WINDOW: "1800",
  RATE_LIMIT_BACKOFF_MULTIPLIER: "2",
  RATE_LIMIT_BACKOFF_MAX_BLOCK_DURATION: "3600",
  
  // ── Authentication & OTP ──────────────────────────────────────────
  SECURITY_OTP_MAX_PER_WINDOW: "5",
  SECURITY_OTP_WINDOW_SECONDS: "3600",
} as const;

export type FamilyPolicy = {
  windowSeconds: number;
  maxHits: number;
  sameTargetWindowSeconds: number;
  sameTargetMaxHits: number;
  exactEndpointWindowSeconds: number;
  exactEndpointMaxHits: number;
  distinctMinuteMax: number;
  distinctHourMax: number;
  distinctDayMax: number;
  scoreBurst: number;
  scoreSameTarget: number;
  scoreExactEndpoint: number;
  scoreDistinct: number;
};

export type SecurityPolicyConfig = {
  enabled: boolean;
  telegramAlertsEnabled: boolean;
  watermarkingEnabled: boolean;
  scoreMedium: number;
  scoreHigh: number;
  scoreCritical: number;
  cooldownSeconds: number;
  contentLockSeconds: number;
  strikeWindowSeconds: number;
  repeatOffenseMultiplier: number;
  aggregationWindowSeconds: number;
  telegramAlertCooldownSeconds: number;
  telegramMinSeverity: SecuritySeverity;
  testSearchResultLimit: number;
  testExplanationDailyHardCap: number;
  testPracticeDailyHardCap: number;
  families: Record<SecurityFamily, FamilyPolicy>;
};

export const SECURITY_FAMILY_LABELS: Record<SecurityFamily, string> = {
  library_structure: "Library Structure",
  library_article: "Library Article",
  library_search: "Library Search",
  library_tooltip: "Library Tooltip",
  test_payload: "Test Payload",
  test_search: "Test Search",
  test_practice: "Test Practice",
  test_explanation: "Test Explanation",
};
